import { CharacteristicsDto } from './dto/characteristics.dto';

export enum Hand {
  left = 'left',
  right = 'right',
}

export enum GameClass {
  warrior = 'warrior',
  knight = 'knight',
  wanderer = 'wanderer',
  thief = 'thief',
  bandit = 'bandit',
  hunter = 'hunter',
  sorcerer = 'sorcerer',
  pyromancer = 'pyromancer',
  cleric = 'cleric',
  deprived = 'deprived',
}

export type GameClasses = {
  [key in GameClass]: CharacteristicsDto;
};

export const gameClasses: GameClasses = {
  [GameClass.warrior]: {
    level: 4,
    vitality: 11,
    attunement: 8,
    endurance: 12,
    strength: 13,
    dexterity: 13,
    resistance: 11,
    intelligence: 9,
    faith: 9,
    perception: 0,
    charisma: 86,
  },
  [GameClass.knight]: {
    level: 5,
    vitality: 14,
    attunement: 10,
    endurance: 10,
    strength: 11,
    dexterity: 11,
    resistance: 10,
    intelligence: 9,
    faith: 11,
    perception: 0,
    charisma: 86,
  },
  [GameClass.wanderer]: {
    level: 3,
    vitality: 10,
    attunement: 11,
    endurance: 10,
    strength: 10,
    dexterity: 14,
    resistance: 12,
    intelligence: 11,
    faith: 8,
    perception: 0,
    charisma: 86,
  },
  [GameClass.thief]: {
    level: 5,
    vitality: 9,
    attunement: 11,
    endurance: 9,
    strength: 9,
    dexterity: 15,
    resistance: 10,
    intelligence: 12,
    faith: 11,
    perception: 0,
    charisma: 86,
  },
  [GameClass.bandit]: {
    level: 4,
    vitality: 12,
    attunement: 8,
    endurance: 14,
    strength: 14,
    dexterity: 9,
    resistance: 11,
    intelligence: 8,
    faith: 10,
    perception: 0,
    charisma: 86,
  },
  [GameClass.hunter]: {
    level: 4,
    vitality: 11,
    attunement: 9,
    endurance: 11,
    strength: 12,
    dexterity: 14,
    resistance: 11,
    intelligence: 9,
    faith: 9,
    perception: 0,
    charisma: 86,
  },
  [GameClass.sorcerer]: {
    level: 3,
    vitality: 8,
    attunement: 15,
    endurance: 8,
    strength: 9,
    dexterity: 11,
    resistance: 8,
    intelligence: 15,
    faith: 8,
    perception: 0,
    charisma: 82,
  },
  [GameClass.pyromancer]: {
    level: 1,
    vitality: 10,
    attunement: 12,
    endurance: 11,
    strength: 12,
    dexterity: 9,
    resistance: 12,
    intelligence: 10,
    faith: 8,
    perception: 0,
    charisma: 84,
  },
  [GameClass.cleric]: {
    level: 2,
    vitality: 11,
    attunement: 11,
    endurance: 9,
    strength: 12,
    dexterity: 8,
    resistance: 11,
    intelligence: 8,
    faith: 14,
    perception: 0,
    charisma: 84,
  },
  [GameClass.deprived]: {
    level: 6,
    vitality: 11,
    attunement: 11,
    endurance: 11,
    strength: 11,
    dexterity: 11,
    resistance: 11,
    intelligence: 11,
    faith: 11,
    perception: 0,
    charisma: 88,
  },
};
