import { Characteristics } from './entities';
import { Equipment } from './equipment/entities';

export enum GameClass {
  warrior = 'warrior',
  knight = 'knight',
  wanderer = 'wanderer',
  thief = 'thief',
  bandit = 'bandit',
  hunter = 'hunter',
  sorcerer = 'sorcerer',
  pyromancer = 'pyromancer',
  cleric = 'cleric',
  deprived = 'deprived',
}

export type GameClasses = {
  [key in GameClass]: {
    characteristics: Omit<Characteristics, 'id'>;
    equipment: Record<
      keyof Omit<Equipment, 'id' | 'souls' | 'humanity'>,
      string | null
    >;
  };
};

const defaultEquipment = {
  helmet: null,
  armor: null,
  arms: null,
  legs: null,
  ring1: null,
  ring2: null,
  left_weapon_primary: null,
  right_weapon_primary: null,
  left_weapon_secondary: null,
  right_weapon_secondary: null,
};

export const gameClasses: GameClasses = {
  [GameClass.warrior]: {
    equipment: {
      ...defaultEquipment,
      legs: 'Hard Leather Boots',
      armor: 'Hard Leather Armor',
      arms: 'Hard Leather Gauntlets',
      helmet: 'Standart Helm',
      left_weapon_primary: 'Heater Shield',
      right_weapon_primary: 'Longsword',
    },
    characteristics: {
      level: 4,
      vitality: 11,
      attunement: 8,
      endurance: 12,
      strength: 13,
      dexterity: 13,
      resistance: 11,
      intelligence: 9,
      faith: 9,
      perception: 0,
      charisma: 9,
    },
  },
  [GameClass.knight]: {
    equipment: {
      ...defaultEquipment,
      legs: 'Knight Leggings',
      armor: 'Knight Armor',
      arms: 'Knight Gauntlets',
      helmet: 'Knight Helm',
      left_weapon_primary: 'Tower Kite Shield',
      right_weapon_primary: 'Broadsword',
    },
    characteristics: {
      level: 5,
      vitality: 14,
      attunement: 10,
      endurance: 10,
      strength: 11,
      dexterity: 11,
      resistance: 10,
      intelligence: 9,
      faith: 11,
      perception: 0,
      charisma: 11,
    },
  },
  [GameClass.wanderer]: {
    equipment: {
      ...defaultEquipment,
      legs: 'Wanderer Boots',
      armor: 'Wanderer Coat',
      arms: 'Wanderer Manchette',
      helmet: 'Wanderer Hood',
      left_weapon_primary: 'Leather Shield',
      right_weapon_primary: 'Scimitar',
    },
    characteristics: {
      level: 3,
      vitality: 10,
      attunement: 11,
      endurance: 10,
      strength: 10,
      dexterity: 14,
      resistance: 12,
      intelligence: 11,
      faith: 8,
      perception: 0,
      charisma: 10,
    },
  },
  [GameClass.thief]: {
    equipment: {
      ...defaultEquipment,
      legs: 'Black Leather Boots',
      armor: 'Black Leather Armor',
      arms: 'Black Leather Gloves',
      helmet: 'Thief Mask',
      left_weapon_primary: 'Target Shield',
      right_weapon_primary: "Bandit's Knife",
    },
    characteristics: {
      level: 5,
      vitality: 9,
      attunement: 11,
      endurance: 9,
      strength: 9,
      dexterity: 15,
      resistance: 10,
      intelligence: 12,
      faith: 11,
      perception: 0,
      charisma: 11,
    },
  },
  [GameClass.bandit]: {
    equipment: {
      ...defaultEquipment,
      legs: 'Brigand Trousers',
      armor: 'Brigand Armor',
      arms: 'Brigand Gauntlets',
      helmet: 'Brigand Hood',
      left_weapon_primary: 'Spider Shield',
      right_weapon_primary: 'Battle Axe',
    },
    characteristics: {
      level: 4,
      vitality: 12,
      attunement: 8,
      endurance: 14,
      strength: 14,
      dexterity: 9,
      resistance: 11,
      intelligence: 8,
      faith: 10,
      perception: 0,
      charisma: 10,
    },
  },
  [GameClass.hunter]: {
    equipment: {
      ...defaultEquipment,
      legs: 'Leather Boots',
      armor: 'Leather Armor',
      arms: 'Leather Gloves',
      left_weapon_primary: 'Large Leather Shield',
      right_weapon_primary: 'Shortsword',
      right_weapon_secondary: 'Short Bow',
    },
    characteristics: {
      level: 4,
      vitality: 11,
      attunement: 9,
      endurance: 11,
      strength: 12,
      dexterity: 14,
      resistance: 11,
      intelligence: 9,
      faith: 9,
      perception: 0,
      charisma: 9,
    },
  },
  [GameClass.sorcerer]: {
    equipment: {
      ...defaultEquipment,
      legs: 'Sorcerer Boots',
      armor: 'Sorcerer Cloak',
      arms: 'Sorcerer Gauntlets',
      helmet: 'Sorcerer Hat',
      left_weapon_primary: 'Small Leather Shield',
      right_weapon_primary: "Sorcerer's Catalyst",
      right_weapon_secondary: 'Dagger',
    },
    characteristics: {
      level: 3,
      vitality: 8,
      attunement: 15,
      endurance: 8,
      strength: 9,
      dexterity: 11,
      resistance: 8,
      intelligence: 15,
      faith: 8,
      perception: 0,
      charisma: 12,
    },
  },
  [GameClass.pyromancer]: {
    equipment: {
      ...defaultEquipment,
      legs: 'Heavy Boots',
      armor: 'Tattered Cloth Robe',
      arms: 'Tattered Cloth Manchette',
      helmet: 'Tattered Cloth Hood',
      left_weapon_primary: 'Cracked Round Shield',
      right_weapon_primary: 'Hand Axe',
      right_weapon_secondary: 'Pyromancy Flame',
    },
    characteristics: {
      level: 1,
      vitality: 10,
      attunement: 12,
      endurance: 11,
      strength: 12,
      dexterity: 9,
      resistance: 12,
      intelligence: 10,
      faith: 8,
      perception: 0,
      charisma: 9,
    },
  },
  [GameClass.cleric]: {
    equipment: {
      ...defaultEquipment,
      legs: 'Holy Trousers',
      armor: 'Holy Robe',
      arms: 'Traveling Gloves',
      helmet: "Priest's Hat",
      left_weapon_primary: 'East-West Shield',
      right_weapon_primary: 'Mace',
    },
    characteristics: {
      level: 2,
      vitality: 11,
      attunement: 11,
      endurance: 9,
      strength: 12,
      dexterity: 8,
      resistance: 11,
      intelligence: 8,
      faith: 14,
      perception: 0,
      charisma: 11,
    },
  },
  [GameClass.deprived]: {
    equipment: {
      ...defaultEquipment,
      left_weapon_primary: 'Plank Shield',
      right_weapon_primary: 'Club',
    },
    characteristics: {
      level: 6,
      vitality: 11,
      attunement: 11,
      endurance: 11,
      strength: 11,
      dexterity: 11,
      resistance: 11,
      intelligence: 11,
      faith: 11,
      perception: 0,
      charisma: 8,
    },
  },
};
