services:
  back:
    build: ../hollow-keeper
    container_name: hollow_back_c
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    volumes:
      - .:/back
      - /back/node_modules
    stdin_open: true
    tty: true
  db:
    restart: always
    image: postgres:15.2
    container_name: hollow_db_c
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hollow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: hollow_pg_admin_c
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  pgadmin_data:
  postgres_data:
